### ISSUE TITLE
Which port to enter in the PlugIn Settings?

### ISSUE THREAD

**Issue by anonimo82** [Ragnaroek/dandelion#10]
Hello everyone.
I installed the Dandelion plugin from the update site, everything fine.
I installed both Common Lisp (2.49.92) AND SBCL (2.0.1).
The plugin requires a port number to "connect" to my Common Lisp interpreter, but I really don't know what to input there, and as I try to "evaluate file" in Eclipse, I get an error: 
![dandelion](https://user-images.githubusercontent.com/38261009/200763304-9c994bce-7d1d-4472-b2e2-20c750d0dc00.png)

What should I do? Note I'm using Linux.

Thanks for any help.

**Comment by anonimo82** [comment]
Update: I made it to execute the file, but now I get a "Connection refused" error: 
![dandelion](https://user-images.githubusercontent.com/38261009/200764557-4831bee4-a84e-4e52-b05a-97cbc5bffa2c.png)

**Comment by anonimo82** [comment]
@Ragnaroek any help?

**Comment by Ragnaroek** [comment]
You did do the `chmod +x <path/to/environment>` thing to get binary executable.
Does this happen in CLISP and SBCL?
Can you start the binary in <path/to/environment> directly in a terminal and post the output of it here?

**Comment by anonimo82** [comment]
I'm not sure, but yes IIRC.
Where should the environment be?

**Comment by anonimo82** [comment]
@Ragnaroek 
Ok, I did it, 101% sure!
But I don't know which port to enter in clisp settings, I don't have a server.

**Comment by anonimo82** [comment]
Nevermind, after building myself the plugin, following the directions in the Wiki, I'm now able to use it.
