### ISSUE TITLE
Dandelion 1.2.3 plugin is not available (at least not for eclipse on linux, neon.1)

### ISSUE THREAD

**Issue by gleibman** [Ragnaroek/dandelion#2]
I'm a current user of Dandelion, having installed it for eclipse ganymede.  But ganymede requires an obsolete version of JRE. Today and yesterday I tried to install dandelion from your website ragnaroek.github.io/dandelion) for a newer release of eclipse, in two ways:
1. In eclipse "adding new software", by typing in your URL and selecting the linux flavors for CLISP and SBCL.
2. By dragging the 'install" icon from github to my running eclipse workbench.  The choices of features
for CLISP and SBCL were again offered for linux, which I chose.

In both cases, I was told that Dandelion was not available.  An alternate process was started which eventually reported that the plugin could not be installed.  Please help!

**Comment by Ragnaroek** [comment]
Hi,
that is strange. Should work out-of-the-box for a fresh Eclipse install (there are some issues with updates).
Can you try to install via the Marketplace (Help > Eclipse Marketplace, Search for Dandelion).

Could you also post the error message (a screenshot would be super helpful)

**Comment by martinbradford** [comment]
Same here - has been failing for some time. I was under the impression that Dandelion was not being actively supported - would love to try it out

**Comment by Ragnaroek** [comment]
> Same here - has been failing for some time. I was under the impression that Dandelion was not being actively supported - would love to try it out

Is this on an update or a fresh install?

**Comment by gleibman** [comment]
These screenshots may clarify my problem in adding Dandelion to Eclipse.  The outcome of all scenarios I have tried (using eclipse update manager, dragging  from marketplace, even trying a fresh install into 2018-12 Eclipse using the new oomph installation component) all lead to screenshot 16-51-49, installing from ragnaroek.github.io/dandelion/.  (The site github.com/Ragnaroek/dandelion, which shows recent Dandelion activity--screenshot 16-6-41--is not even recognized by Eclipse as a download site.)  In screenshot 16-51-49 you can see that the features for SBCL for the linux operating system--which I need--are not even offered, even though they are listed as currently available on that website (ragnaroek.github.io/dandelion/, see screenshot 16-4-25.)  Perhaps there have been changes in the protocol for serving products on github?  Any help is appreciated...
George Leibman

![screenshot from 2019-01-11 16-51-49](https://user-images.githubusercontent.com/46569754/51091239-0a5cf000-1756-11e9-8e48-d22cb535afce.png)
![screenshot from 2019-01-13 16-04-25](https://user-images.githubusercontent.com/46569754/51091241-0df07700-1756-11e9-8170-2da13da7ef6f.png)
![screenshot from 2019-01-13 16-06-41](https://user-images.githubusercontent.com/46569754/51091242-10eb6780-1756-11e9-8367-ccaa2db341ea.png)
