### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Nuube** [Ragnaroek/dandelion#3]
I tried to install Dandelion and I ran in the same problems as vindarei was reporting in December.

I am in a Manjaro Linux environment. When I tried to install Dandelion from Eclipse using the marketplace, I am offered a Linux version (next to a mandatory Mac version):

![grafik](https://user-images.githubusercontent.com/25643142/54032960-5d31b180-41b3-11e9-9239-fe4472104c36.png)

But cannot install:

![grafik](https://user-images.githubusercontent.com/25643142/54033061-9b2ed580-41b3-11e9-9225-ae641e65f7d1.png)

![grafik](https://user-images.githubusercontent.com/25643142/54033249-18f2e100-41b4-11e9-90af-32ecccada632.png)

When I try to install by help->install new software the Linux version is not displayed at all:

![grafik](https://user-images.githubusercontent.com/25643142/54032859-0fb54480-41b3-11e9-9b25-e00eb176e3e1.png)

**Update:** I can not install the downloaded jar as a local file either ("Could not find jaŕ file", instead of the correct file was selected from browsing the directory) 

It's a bit like eclipse does not  accept it as a jar file. Maybe the jar file is corrupt?

**Comment by Ragnaroek** [comment]
I assume the platform filter is not working correctly (for whatever reason). I had some issues with it in the past and will remove it.

**Comment by osoroed** [comment]
This is still not letting me install on linux.

**Comment by Ragnaroek** [comment]
@osoroed Can you try again, I updated the Update Site with a new version
