### ISSUE TITLE
64-bit mac issues

### ISSUE THREAD

**Issue by benknoble** [Ragnaroek/dandelion#5]
I TA a programming languages class where it is convenient for students to use CLISP in Eclipse using this plugin.

A number of issues have been reported that dandelion installs correctly on macs, but doesn't run.

On my machine, after making the binary executable, Eclipse cannot connect. Checking on the commandline:

```bash
# file binary/environment_clisp_2.49.2
binary/environment_clisp_2.49.2: Mach-O executable i386
# ldd binary/environment_clisp_2.49.2
binary/environment_clisp_2.49.2:
	/opt/local/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.2.0)
	/opt/local/lib/libiconv.2.dylib (compatibility version 8.0.0, current version 8.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 744.18.0)
	/opt/local/lib/libreadline.6.2.dylib (compatibility version 6.0.0, current version 6.2.0)
	/opt/local/lib/libncurses.5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/opt/local/lib/libsigsegv.2.dylib (compatibility version 3.0.0, current version 3.2.0)
# ./binary/environment_clisp_2.49.2
dyld: Library not loaded: /opt/local/lib/libintl.8.dylib
  Referenced from: /Users/Knoble/.p2/pool/plugins/de.defmacro.dandelion.env.clisp.mac.intel_2.49.2/./binary/environment_clisp_2.49.2
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libintl.8.dylib: mach-o, but wrong architecture
	/usr/local/Cellar/gettext/0.20.2_1/lib/libintl.8.dylib: mach-o, but wrong architecture
zsh: abort      ./binary/environment_clisp_2.49.2
# file /usr/local/lib/libint*
/usr/local/lib/libintl.8.dylib: Mach-O 64-bit dynamically linked shared library x86_64
/usr/local/lib/libintl.a:       current ar archive random library
/usr/local/lib/libintl.dylib:   Mach-O 64-bit dynamically linked shared library x86_64
```

I wonder if you might be able to compile a 64-bit compatible executable and share it? I have clisp installed separately, but not the dandelion server code, so I couldn't add a special configuration myself in Eclipse's preferences that worked (just connections refused).

I'll also note that I managed to point `DYLD_LIBRARY_PATH` at a directory with a universal dylib with both architectures, and then it bailed for readline—my readline version is "too new," so I couldn't make that work. 

Alternately, perhaps you could provide the necessary libs alongside the binary? Pre-Catalina (which won't run 32-bit), that should work.

---

My student with the issue reports

```
Starting eval server failed
Cannot run program "/Users/xxx/.p2/pool/plugins/de.defmacro.dandelion.env.clisp.mac.intel_2.49.2/binary/environment_clisp_2.49.2": error=86, Bad CPU type in executable
```

**Comment by Ragnaroek** [comment]
Hi Ben,

yes the CLISP version is pretty old. I will try to update the version with a recent one (but it may take a week).
CLISP doesn't look maintained anymore. Would it be an option to switch to SBCL?

Best regards,
Michael

**Comment by phoe** [comment]
Yes, please switch to SBCL. [CLISP](https://gitlab.com/gnu-clisp/clisp/-/commits/master) is little maintained.

**Comment by Ragnaroek** [comment]
Gave it a try, hit this error in split-sequence: https://github.com/sharplispers/split-sequence/issues
I'll wait what they are saying there to the CLISP support.

**Comment by phoe** [comment]
You need to manually upgrade ASDF to a more recent version in order to load split-sequence into CLISP.

**Comment by Ragnaroek** [comment]
Yes, this needs to be done _before_ quicklisp is loaded. With that I can at least build the binary in CLISP now!
I now need to check if the binary is working fine (will do that later)

**Comment by benknoble** [comment]
Thanks for the support! We're investigating alternatives, but keep us posted!

**Comment by Ragnaroek** [comment]
Doesn't look good for CLISP. I can produce a binary, but this binary cannot be started and gives me the error `module 'syscalls' requires package OS`. After a little investigation it looks like a bug in CLISP.
Maybe somebody has an idea how to fix this? Otherwise I have to drop CLISP support, because it is not maintained anymore.

**Comment by phoe** [comment]
I suggest to file an issue on the CLISP tracker at https://gitlab.com/gnu-clisp/clisp and drop its support until it's fixed and maintained. One more thing is that you could try if building the newest version of CLISP from source solves your problem; there hasn't been an official CLISP release for years.

**Comment by Ragnaroek** [comment]
The latest CLISP version (2.49.93+) build on my machine works! I will prepare a CLISP update.

**Comment by Ragnaroek** [comment]
The clisp update is now live on https://ragnaroek.github.io/dandelion/ @benknoble can you check if it working for you?

**Comment by benknoble** [comment]
@Ragnaroek I get an error saying the document could not be downloaded by my browser when I follow that link; are you sure it's correct? Not sure what I'm supposed to see

**Comment by Ragnaroek** [comment]
@benknoble Yes, I also get this error if I open the page in a webbrowser. This is the Update Site for Eclipse. If you check for updates in Eclipse you should now get the update with the new CLISP version.

**Comment by benknoble** [comment]
Alright, trying this now.

FWIW, students will have the option to use Dandelion as editor-only (running programs in the interpreter on the command line), but we _hugely_ appreciate your support on this.

**Comment by benknoble** [comment]
This worked! Had to `chmod` again, but this worked! Thank you :)

**Comment by Ragnaroek** [comment]
Glad that it worked for you! And many thanks to @phoe for all the hints on how to solve this :)

**Comment by benknoble** [comment]
I will note that, at least for me, if I issue `(quit)` and then try to run "Evaluate file," I get connection refused errors (looks like it's not restarting the interpreter?). But that's workable... just don't quit :) I may try SBCL and see what's what. Thanks again.

**Comment by phoe** [comment]
`(sb-ext:quit)` is the function used to kill the running Lisp image, which works as intended. If you don't want to quit Lisp, then you shouldn't quit it.

**Comment by benknoble** [comment]
@phoe in clisp, I wouldn't expect that to be defined... any of `(quit)`, `(exit)`, or `(bye)` work at the command line—as you say, they stop the running lisp image.

But I also expect to be able to kill the current interpreter and start a new one later (as at the command line). The plugin may not support that, which is fine, but I need to know if so.

**Comment by phoe** [comment]
CLISP has the symbols `ext:quit`, `ext:exit`, and `ext:bye`, which seem to perform the same thing. Anyway, these are low-level commands that interact directly with the Lisp image; this works in the same way in Slime.

Slime actually has its own command, `restart-inferior-lisp`, for rebooting the running Lisp image; this functionality is distinct from simply shutting the Lisp image down. Perhaps Dandelion has something similar?

**Comment by Ragnaroek** [comment]
No, there is currently no restart in Dandelion. If you execute `(quit)` you basically terminate the interpreter process and that's it then for the current Eclipse session. Auto-Restart would totally make sense, but it's not implemented yet.
