### ISSUE TITLE
might not ben an issue, 

### ISSUE THREAD

**Issue by validset** [Ragnaroek/dandelion#7]
Not really an issue, feel free to close.

I am new to lisp but been with eclipse for a bit.

Is there a way to change colours of quoted text? Such as  (5 (format t "~% Friday"))  ~%Friday is very dark blue.

I am using highcontrast dark theme native from windows and there is no setting in eclipse that lets you colours in fonts that lets me change it.

Can I increase listener font size? just little small.

AND is there a way to enable auto add closing parenthesis and change how many spaces are added when I hit the return key? 

Only on windows, only clisp 2.49.2 works for me, but it works great. I manually added windows 2.0.0 SBCL and no luck connecting. 

Overall great software!

;;edited for better english

**Comment by Ragnaroek** [comment]
Unfortunately the styles are all hardcoded and cannot be changed (https://github.com/Ragnaroek/dandelion/blob/master/Dandelion/src/de/defmacro/dandelion/internal/ui/text/presentation/SyntaxHighlightingDefinition.java).

That would be a nice enhancement, but there are currently no plans for adding this.

The blue background does not go well with the Eclipse dark mode. Maybe switching to the non-dark mode would make it more readable for you?

Also auto-closing parenthesis and configuring the indentation level would be an enhancement.

The issues with SBCL on windows is known (https://github.com/Ragnaroek/dandelion/issues/6). Looks like a problem with SBCL, which is not very maintained on windows.

Feel free to add new issues with Labels 'enhancement' for the features that you are missing in dandelion.
